# default configuration to Alpha
config: &default
  server: &server
    timeout: 15
    shutdownTimeout: 15
    port: 3000
    name: url-shortener
    env: local
  redis: &redis
    key: "shortner:"
    expire: 30 #Days
    redisServer:
      address: 127.0.0.1
      port: 6379

local:
  <<: *default
  server:
    <<: *server
  redis:
    <<: *redis